name: max_bot_api
description: Max Bot API Client for Dart - a framework for building bots for Max messenger
version: 0.0.1
repository: https://github.com/serezhia/max-bot-api-client-dart

environment:
  sdk: ^3.5.0

dependencies:
  http: ^1.2.2
  meta: ^1.15.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
